[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
optimizer = true
optimizer_runs = 200
solc='0.8.26'
evm_version = 'paris'
bytecode_hash = 'none'
ignored_warnings_from = ["src/periphery/contracts/treasury/RevenueSplitter.sol"]
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{access = "write", path = "./reports"}, {access = "read", path = "./out" }, {access = "read", path = "./config"}]
ffi = true

[profile.zksync]
solc = '0.8.26'
fs_permissions = [{access = "write", path = "./reports"}, {access = "read", path = "./out" }, {access = "read", path = "./config"}]
ffi = true
evm_version = 'paris'

[profile.zksync.zksync]
bytecode_hash = 'none'
compile = true
fallback_oz = true
mode = '3'
zksolc = '1.5.3'

[fuzz]
runs = 1000
max_test_rejects = 400000

[invariant]
runs = 25
depth = 1000
fail_on_revert = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
